### ISSUE TITLE
Sample needed

### ISSUE THREAD

**Issue by skaag** [LordGaav/proxmox-deploy#1]
It would be wonderful if you could provide a sample script which uses this tool to deploy an image onto a Proxmox server, in non-interactive mode, along with a custom install script for the OS (Ubuntu for example).

**Comment by LordGaav** [comment]
Unfortunately, the non-interactive mode is not yet developed. Only the interactive mode is available, for which instructions can be found in the README:

https://github.com/LordGaav/proxmox-deploy#how-to-use
