### ISSUE TITLE
volume local-lvm:vm-3000-cloudinit-seed does not exists

### ISSUE THREAD

**Issue by travka** [LordGaav/proxmox-deploy#12]
openssh_wrapper.SSHError: qemu-img: Could not open '/dev/pve/vm-3000-cloudinit-seed': Could not open '/dev/pve/vm-3000-cloudinit-seed
': No such file or directory
volume local-lvm:vm-3000-cloudinit-seed does not exists

:(

**Comment by LordGaav** [comment]
https://upthemes.com/blog/2014/02/writing-useful-github-issues/
