### ISSUE TITLE
User creation

### ISSUE THREAD

**Issue by travka** [LordGaav/proxmox-deploy#13]
Hey, I plain to use your code in production, but i have some weird problems.
1. If network-config is wrong, i can't access to machine via pubkey.
Is there's any chance that you will add a user password add with sudo or something like this ?

**Comment by LordGaav** [comment]
No, not at this time. I find that configuring an username and password is very insecure.

However, cloud-init supports setting a password, so perhaps you can tweak the template to add an user to your liking. Also see: http://cloudinit.readthedocs.io/en/latest/topics/examples.html .
