### ISSUE TITLE
Specify SSH port

### ISSUE THREAD

**Issue by dorogarcia** [LordGaav/proxmox-deploy#7]
Hello again,

Should be nice if you can add a new option from cli to specify port:

/usr/local/lib/python2.7/dist-packages/proxmoxdeploy/cli.py line: 88

`
    api = ProxmoxClient(ProxmoxAPI(args.proxmox_host, port="CUSTOM_PORT", timeout=600,
                                   user=args.proxmox_user, backend="openssh"))
`

Thanks!

**Comment by LordGaav** [comment]
Indeed.
